name: Test Custom Port

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: graphnode
          POSTGRES_PASSWORD: password
          POSTGRES_DB: graphnode-db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      ipfs:
        image: ipfs/kubo:v0.17.0
        ports:
          - 5001:5001
    steps:
      - uses: actions/checkout@v4
      - name: Start Anvil
        uses: iExecBlockchainComputing/anvil-github-action@v1.0.0

      - name: Wait kubo
        run: |
          chmod +x ./wait-for-it.sh
          ./wait-for-it.sh localhost:5001 -t 0

      # Start Graph Node server
      - name: Start Graph Node server
        uses: ./
        with:
          port: 1234
          admin-port: 4321
          postgres_host: postgres
          postgres_user: graphnode
          postgres_db: graphnode-db
          postgres_pass: password
          ipfs_host: ipfs
          ethereum: 'bellecour:http://localhost:8545'

      - uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
        env:
          CI: true
