name: Validate action typings

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  validate-typings:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - uses: typesafegithub/github-actions-typing@v2
